name: Release

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release:
    uses: do-ob-io/shared/.github/workflows/release-please.yml@main
    secrets: inherit